### ISSUE TITLE
ReferenceError: btoa is not defined

### ISSUE THREAD

**Issue by gunesacar** [StotoV/sri-checker#32]
Received a ReferenceError for `btoa`. Maybe it's because of my node version:
https://github.com/StotoV/sri-checker/blob/39d128252c82ba1f4ed556f354f843743926ced7/src/scrape.js#L129

Perhaps we can change it with: `let filename = Buffer.from(target).toString('base64');`

We could also consider including the hostname of the target so the files are more human readable, but that's an optional feature.
Here's how Tracker Radar Collector name files:

- https://github.com/duckduckgo/tracker-radar-collector/blob/98573103f11eb0a830e93a26bab77dd2a040339c/helpers/hash.js#L7
- https://github.com/duckduckgo/tracker-radar-collector/blob/98573103f11eb0a830e93a26bab77dd2a040339c/cli/crawl-cli.js#L76

**Comment by StotoV** [comment]
Made the btoa change!
As there will be around 5 to 10 million files in the output directory I think the current base64 implementation will suffice as the data needs to be parsed anyways to be usable (executing the ls command takes around a minute for me).
