### ISSUE TITLE
Add tests for dynamically injected script tags

### ISSUE THREAD

**Issue by gunesacar** [StotoV/sri-checker#9]
Scripts may dynamically inject iframes, which may contain script tags that may fail the SRI check. The main advantage of using a JS-enabled browser such as Puppeteer (over e.g., a `requests`-based solution) is the ability to validate such dynamically added iframes/script tags.

Let's make sure to add a test case to demonstrate this difference.

We'd just need to inject an iframe containing some third-party script tags.
https://stackoverflow.com/a/3069972

We may have tests for the following; (just to give ideas, not concrete suggestions):
`should_fail_for_dynamically_added_scripts_without_sri_attrs` 
`should_fail_for_dynamically_added_scripts_with_invalid_sri_attrs`
`should_pass_for_dynamically_added_scripts_with_valid_sri_attrs`

**Comment by StotoV** [comment]
Done. I've only written the invalid sri test though, as the important part is that the tag is correctly discovered. If it is discovered the other tests will also function for the rest of the cases.
